### ISSUE TITLE
v0.3.0 release tracker

### ISSUE THREAD

**Issue by durandtibo** [durandtibo/coola#380]
## Equality
- [x] default #359 
- [x] `scalar`/`nan` #416
- [x] `Mapping` #373 
- [x] `Sequence` #370
- [x] [`jax.numpy.ndarray`](https://jax.readthedocs.io/en/latest/index.html) #379
- [x] [`numpy.ndarray`](https://numpy.org/doc/stable/index.html) #363 
- [x]  [`numpy.ma.MaskedArray`](https://numpy.org/doc/stable/reference/maskedarray.generic.html) #401 #414
- [x] [`pandas.DataFrame`](https://pandas.pydata.org/) #398
- [x] [`pandas.Series`](https://pandas.pydata.org/) #397 
- [x] [`polars.DataFrame`](https://www.pola.rs/) #400
- [x] [`polars.Series`](https://www.pola.rs/) #400
- [x] [`torch.Tensor`](https://pytorch.org/) #368 
- [x] [`torch.nn.utils.rnn.PackedSequence`](https://pytorch.org/) #387 
- [x] [`xarray.DataArray`](https://docs.xarray.dev/en/stable/) #392
- [x] [`xarray.Dataset`](https://docs.xarray.dev/en/stable/) #390
- [x] [`xarray.Variable`](https://docs.xarray.dev/en/stable/) #389 

## Close
- [x] default
- [x] scalar/`nan`
- [x] `Mapping` 
- [x] `Sequence` 
- [x] [`jax.numpy.ndarray`](https://jax.readthedocs.io/en/latest/index.html)
- [x] [`numpy.ndarray`](https://numpy.org/doc/stable/index.html)
- [x] [`numpy.ma.MaskedArray`](https://numpy.org/doc/stable/reference/maskedarray.generic.html)
- [x] [`pandas.DataFrame`](https://pandas.pydata.org/)
- [x] [`pandas.Series`](https://pandas.pydata.org/)
- [x] [`polars.DataFrame`](https://www.pola.rs/)
- [x] [`polars.Series`](https://www.pola.rs/)
- [x] [`torch.Tensor`](https://pytorch.org/)
- [x] [`torch.nn.utils.rnn.PackedSequence`](https://pytorch.org/)
- [x] [`xarray.DataArray`](https://docs.xarray.dev/en/stable/)
- [x] [`xarray.Dataset`](https://docs.xarray.dev/en/stable/)
- [x] [`xarray.Variable`](https://docs.xarray.dev/en/stable/)

**Comment by durandtibo** [comment]
TODO: add support for sparse torch Tensors
